language: php

php:
# - 5.3 # requires old distro, see below
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

# lock distro so future defaults will not break the build
dist: trusty

matrix:
  include:
    - php: 5.3
      dist: precise

install:
  - composer install --no-interaction

script:
  - vendor/bin/phpunit --coverage-text
